#!/bin/bash

SERIE_URL="derived-mesh"
BRANCH="blender2.8"
QUERY="grep -r -H --color=never -H -e 'DerivedMesh' . | grep -v cdderivedmesh.c | grep -v DerivedMesh.c | grep -v subsurf_ccg.c | wc -l"

grafista-blender "$SERIE_URL" "$BRANCH" "$QUERY"
