#!/bin/bash

SERIE_URL="immediate_mode"
BRANCH="blender2.8"
QUERY="grep -r -H --color=never -H -e glBegin\( -e glEnd\( -e glVertex[^A] -e glNormal -e glTexCoord -e fdrawline -e fdrawbox -e fdrawbox_filled -e fdrawcheckboard -e sdrawline -e sdrawbox . | wc -l"

grafista-blender "$SERIE_URL" "$BRANCH" "$QUERY"
