#!/bin/bash

BLENDER=$HOME/src/blender/grafista
GRAFISTA=$HOME/src/web-dev/grafista

if [ "$#" != 3 ]  && [ "$#" != 4 ] ; then
  echo "Wrong number of parameters specified ($#) ... use 'h' for help. Exiting."
  exit 0

elif [ "$LINE" == "h" ] ; then

  echo "grafista-blender serie_url branch query (before)"
  exit 0
fi

SERIE_URL=$1
BRANCH=$2
QUERY=$3

# optional date reference, used to update
BEFORE=$4

# get latest blender
cd $BLENDER
git fetch

if [ "$BEFORE" != "" ] ; then
  HASH=`git rev-list -1 --first-parent --before="$BEFORE" origin/$BRANCH`
  echo "Hash: $HASH"
  echo "Date: $BEFORE"
  `git checkout $HASH`
else
  `git checkout origin/$BRANCH`
fi

count=`eval $QUERY`

# update database
cd $GRAFISTA
source venv/bin/activate

if [ "$BEFORE" != "" ] ; then
  DATE=$(date -d "$BEFORE" +%Y%m%d)
  flask series insert_sample $SERIE_URL $count -t "$DATE"
else
  flask series insert_sample $SERIE_URL $count
fi
