#!/bin/bash

SERIE_URL="immediate_mode"
BRANCH="blender2.8"
QUERY="grep -r -H --color=never -H \
    -e fdrawbox \
    -e fdrawbox_filled \
    -e fdrawcheckerboard \
    -e fdrawline \
    -e glBegin\( \
    -e glColor[^M] \
    -e glDisableClientState \
    -e glEnableClientState \
    -e glEnd\( \
    -e glNormal \
    -e glRect \
    -e glTexCoord \
    -e glVertex[^A] \
    -e glVertexPointer \
    -e sdrawline \
    -e sdrawbox \
    -e UI_ThemeColor \
  . | wc -l"

# optional parameter used to re-generate data sequences
BEFORE="$1"

grafista-blender "$SERIE_URL" "$BRANCH" "$QUERY" "$BEFORE"
