#!/bin/bash

SERIE_URL="immediate_mode"
BRANCH="blender2.8"
QUERY="grep -r -H --color=never -H -e glBegin\( -e glEnd\( -e glVertex[^A] -e glNormal -e glTexCoord . | wc -l"

grafista-blender "$SERIE_URL" "$BRANCH" "$QUERY"
